# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb17d449200213528b94b69b4b7d92134fe10676ecfc28245f8ba6283ddb466e1b57b21484c48ed6fed7e6fc8b38078b57959f9277cd28690320f24e18867380

test:
  secret_key_base: 23ebb9b9bde91b3ccce27b9de57a62b9655cf039e9b0995ef82472c294ee13da905c871f57316324ecf5cd20f2e0c926a4a24d4f009e83cd89468e5711c51daf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
